
package VISTA;

import MODELO.ClienteClase;
import MODELO.ClienteDAO;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class Clientes extends javax.swing.JFrame {

    ClienteClase cl = new ClienteClase();
    ClienteDAO client = new ClienteDAO();
    DefaultTableModel modelo;
    
    public Clientes() {
        initComponents();
        this.setBounds(0,0,1920,1080);
        this.setLocationRelativeTo(null);
        
    }
    public void ListarCliente(){
        List<ClienteClase> ListaCl = client.ListarCliente();
        modelo = (DefaultTableModel) TbClient.getModel();
        Object[] ob = new Object[5];
        for (int i = 0; i < ListaCl.size(); i++){
            ob[0] = ListaCl.get(i).getDni_client();
            ob[1] = ListaCl.get(i).getNom_client();
            ob[2] = ListaCl.get(i).getApell_client();
            ob[3] = ListaCl.get(i).getDirecc_client();
            ob[4] = ListaCl.get(i).getTelef_client();
            modelo.addRow(ob);
        }
        TbClient.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Cerrar = new javax.swing.JButton();
        Venta = new javax.swing.JButton();
        Mueble = new javax.swing.JButton();
        Categoria = new javax.swing.JButton();
        Pedidos = new javax.swing.JButton();
        Clientes = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DniClient = new javax.swing.JTextField();
        NomClient = new javax.swing.JTextField();
        DireccClient = new javax.swing.JTextField();
        TelefClient = new javax.swing.JTextField();
        vertodos = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbClient = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        ApellClient = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(55, 160, 244));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CLIENTES");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(1540, 20, 160, 48);

        Cerrar.setBackground(new java.awt.Color(55, 160, 244));
        Cerrar.setForeground(new java.awt.Color(255, 255, 255));
        Cerrar.setText("CERRAR SESIÓN");
        jPanel2.add(Cerrar);
        Cerrar.setBounds(1760, 20, 140, 40);

        Venta.setBackground(new java.awt.Color(55, 160, 244));
        Venta.setForeground(new java.awt.Color(255, 255, 255));
        Venta.setText("VENTAS");
        jPanel2.add(Venta);
        Venta.setBounds(80, 20, 110, 40);

        Mueble.setBackground(new java.awt.Color(55, 160, 244));
        Mueble.setForeground(new java.awt.Color(255, 255, 255));
        Mueble.setText("MUEBLES");
        jPanel2.add(Mueble);
        Mueble.setBounds(200, 20, 110, 40);

        Categoria.setBackground(new java.awt.Color(55, 160, 244));
        Categoria.setForeground(new java.awt.Color(255, 255, 255));
        Categoria.setText("CATEGORIA");
        jPanel2.add(Categoria);
        Categoria.setBounds(320, 20, 110, 40);

        Pedidos.setBackground(new java.awt.Color(55, 160, 244));
        Pedidos.setForeground(new java.awt.Color(255, 255, 255));
        Pedidos.setText("PEDIDOS");
        jPanel2.add(Pedidos);
        Pedidos.setBounds(440, 20, 110, 40);

        Clientes.setBackground(new java.awt.Color(55, 160, 244));
        Clientes.setForeground(new java.awt.Color(255, 255, 255));
        Clientes.setText("CLIENTES");
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        jPanel2.add(Clientes);
        Clientes.setBounds(560, 20, 110, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1920, 90);

        jLabel6.setText("©2024SamuelRueda. Todos los derechos reservados");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(240, 980, 290, 16);

        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(55, 160, 244)));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(310, 370, 480, 50);

        jButton1.setBackground(new java.awt.Color(55, 160, 244));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Iconos/search.png"))); // NOI18N
        jPanel1.add(jButton1);
        jButton1.setBounds(240, 370, 50, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("DNI DEL CLIENTE:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(840, 180, 210, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("NOMBRE DEL CLIENTE:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(840, 230, 210, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("DIRECCIÓN DEL CLIENTE:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(840, 330, 210, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("TELEFONO DEL CLIENTE:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(840, 380, 210, 40);

        DniClient.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(55, 160, 244)));
        jPanel1.add(DniClient);
        DniClient.setBounds(1080, 180, 350, 40);

        NomClient.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(55, 160, 244)));
        jPanel1.add(NomClient);
        NomClient.setBounds(1080, 230, 350, 40);

        DireccClient.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(55, 160, 244)));
        jPanel1.add(DireccClient);
        DireccClient.setBounds(1080, 330, 350, 40);

        TelefClient.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(55, 160, 244)));
        jPanel1.add(TelefClient);
        TelefClient.setBounds(1080, 380, 350, 40);

        vertodos.setBackground(new java.awt.Color(55, 160, 244));
        vertodos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vertodos.setForeground(new java.awt.Color(255, 255, 255));
        vertodos.setText("VER TODOS");
        vertodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vertodosActionPerformed(evt);
            }
        });
        jPanel1.add(vertodos);
        vertodos.setBounds(1470, 370, 130, 50);

        guardar.setBackground(new java.awt.Color(55, 160, 244));
        guardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("GUARDAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar);
        guardar.setBounds(1470, 190, 130, 50);

        eliminar.setBackground(new java.awt.Color(55, 160, 244));
        eliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setText("ELIMINAR");
        jPanel1.add(eliminar);
        eliminar.setBounds(1470, 250, 130, 50);

        modificar.setBackground(new java.awt.Color(55, 160, 244));
        modificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setText("MODIFICAR");
        jPanel1.add(modificar);
        modificar.setBounds(1470, 310, 130, 50);

        TbClient.setAutoCreateRowSorter(true);
        TbClient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TbClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "NOMBRE", "APELLIDO", "DIRECCIÓN", "TELEFONO"
            }
        ));
        TbClient.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TbClient.setGridColor(new java.awt.Color(204, 204, 204));
        TbClient.setRowHeight(35);
        TbClient.setSelectionBackground(new java.awt.Color(85, 183, 252));
        TbClient.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TbClient.setShowGrid(true);
        jScrollPane2.setViewportView(TbClient);
        if (TbClient.getColumnModel().getColumnCount() > 0) {
            TbClient.getColumnModel().getColumn(0).setMinWidth(220);
            TbClient.getColumnModel().getColumn(0).setPreferredWidth(220);
            TbClient.getColumnModel().getColumn(0).setMaxWidth(220);
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(220, 460, 1390, 380);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("APELLIDO DEL CLIENTE:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(840, 280, 210, 40);

        ApellClient.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(55, 160, 244)));
        jPanel1.add(ApellClient);
        ApellClient.setBounds(1080, 280, 350, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1010);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        if(!"".equals(DniClient.getText()) || !"".equals(NomClient.getText()) || !"".equals(ApellClient.getText()) || !"".equals(DireccClient.getText()) || !"".equals(TelefClient.getText())){
            cl.setDni_client(Integer.parseInt(DniClient.getText()));
            cl.setNom_client(NomClient.getText());
            cl.setApell_client(ApellClient.getText());
            cl.setDirecc_client(DireccClient.getText());
            cl.setTelef_client(TelefClient.getText());
            client.RegistrarCliente(cl);
            JOptionPane.showMessageDialog(null, "Cliente Registrado");
        }
        else{
            JOptionPane.showMessageDialog(null, "Los campos estan vacion");
        }
        ListarCliente();
        DniClient.setText("");
        NomClient.setText("");
        ApellClient.setText("");
        DireccClient.setText("");
        TelefClient.setText("");
    }//GEN-LAST:event_guardarActionPerformed

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        
    }//GEN-LAST:event_ClientesActionPerformed

    private void vertodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vertodosActionPerformed
        ListarCliente();
    }//GEN-LAST:event_vertodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellClient;
    private javax.swing.JButton Categoria;
    private javax.swing.JButton Cerrar;
    private javax.swing.JButton Clientes;
    private javax.swing.JTextField DireccClient;
    private javax.swing.JTextField DniClient;
    private javax.swing.JButton Mueble;
    private javax.swing.JTextField NomClient;
    private javax.swing.JButton Pedidos;
    private javax.swing.JTable TbClient;
    private javax.swing.JTextField TelefClient;
    private javax.swing.JButton Venta;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton modificar;
    private javax.swing.JButton vertodos;
    // End of variables declaration//GEN-END:variables
}
